const DOMAIN = process.env.REACT_APP_URL_BACKEND_OAUTH2;

const DOMAIN_FRONTEND = process.env.REACT_APP_FRONT_DOMAIN;

export const URL_BACKEND_OAUTH2 = `${DOMAIN}/oauth2/authorize/google?redirect_uri=`;

export const LOGIN_DOMAIN = DOMAIN;

export const URL_FRONTEND = `${DOMAIN_FRONTEND}/redirect`;

export const PERMISSIONS_STORAGE_KEY = "permissions";

export const USER_STORAGE_KEY = "user";

export const ACCESS_TOKEN_STORAGE_KEY = "access_token";

export const REFRESH_TOKEN_STORAGE_KEY = "refresh_token";

export const USER_TYPE_STORAGE_KEY = "user_type";

export const MODULE_AVAILABLE_STORAGE_KEY = "module_available";

export const USER_ID_STORAGE_KEY = "user_id";

export const URL_WEBSOCKET = `${DOMAIN}/ws-message`;

export enum PERMISSIONS {
  BAN_DAO_TAO_HO = "BAN_DAO_TAO_HO",
  ADMIN = "ADMIN",
  TRUONG_BAN_DAO_TAO_CO_SO = "TRUONG_BAN_DAO_TAO_CO_SO",
  QUAN_LY_DAO_TAO = "QUAN_LY_DAO_TAO",
  CHU_NHIEM_BO_MON = "CHU_NHIEM_BO_MON",
  TRUONG_MON_CHUYEN_NGANH = "TRUONG_MON_CHUYEN_NGANH",
  GIAO_VIEN = "GIAO_VIEN",
  SINH_VIEN = "SINH_VIEN",
}

export const ALL_PERMISSIONS = [
  PERMISSIONS.BAN_DAO_TAO_HO,
  PERMISSIONS.ADMIN,
  PERMISSIONS.TRUONG_BAN_DAO_TAO_CO_SO,
  PERMISSIONS.QUAN_LY_DAO_TAO,
  PERMISSIONS.CHU_NHIEM_BO_MON,
  PERMISSIONS.TRUONG_MON_CHUYEN_NGANH,
  PERMISSIONS.GIAO_VIEN,
  PERMISSIONS.SINH_VIEN,
];

export const HTTP_STATUS = {
  OK: "OK",
  CREATED: "CREATED",
  NO_CONTENT: "NO_CONTENT",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
