name: job deploy server
 
on:
  push:
    branches:
      - 'deploy_config'

jobs:
  build_marketplace:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./BE
          file: ./BE/Dockerfile
          push: true
          tags: truongsondev/backend:v1.0
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./FE
          file: ./FE/Dockerfile
          push: true
          tags: truongsondev/client:v1.0
      - 
       name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.PORT }}
         script: |
            cd deploy-compose
            docker pull truongsondev/backend:v1.0
            docker pull truongsondev/client:v1.0
            docker-compose up -d --build web_event
            docker-compose up -d --build api_event
            docker restart nginx-proxy
            docker image prune
    
        
  notifi_slack_bot:
    runs-on: ubuntu-latest
    needs: ['build_marketplace']
    steps:
      - name: Slack Notification Ci/Cd started
        uses: 8398a7/action-slack@v3.15.1
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "Dự án quản lý sự kiện đã được deploy lên server, mọi người truy cập vào đường dẫn https://event.udpm-hn.com để check nhé !!!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
